server:
  port: 8443
  ssl:
    certificate: classpath:server-cert.pem
    certificate-private-key: classpath:server-key-unencrypted.pem
    trust-certificate: classpath:client-cert.pem
    client-auth: need

